"""user model changed

Revision ID: 2f0a2c2d02b1
Revises: 3de45e2b9211
Create Date: 2021-01-31 23:29:05.276468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0a2c2d02b1'
down_revision = '3de45e2b9211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'users', ['reset_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
