"""user model changed

Revision ID: 3de45e2b9211
Revises: 790d804ce324
Create Date: 2021-01-31 23:12:13.344741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de45e2b9211'
down_revision = '790d804ce324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
