"""relations changed

Revision ID: 540a290a4cf0
Revises: f0bbd5eb32d4
Create Date: 2021-01-16 14:08:46.462121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540a290a4cf0'
down_revision = 'f0bbd5eb32d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'language', ['language_id'], ['language_id'])
    op.add_column('lessons', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lessons', 'language', ['language_id'], ['language_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'language_id')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'language_id')
    # ### end Alembic commands ###
