"""initial

Revision ID: 7de13f5bb471
Revises: 
Create Date: 2021-01-13 12:40:48.540515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de13f5bb471'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continents',
    sa.Column('continent_id', sa.Integer(), nullable=False),
    sa.Column('continent_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('continent_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=200), nullable=False),
    sa.Column('country_image', sa.Text(), nullable=False),
    sa.Column('cont_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cont_id'], ['continents.continent_id'], ),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('language',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=200), nullable=False),
    sa.Column('language_image', sa.Text(), nullable=False),
    sa.Column('con_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['con_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('language_id')
    )
    op.create_table('level',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=200), nullable=False),
    sa.Column('level_image', sa.Text(), nullable=False),
    sa.Column('lang_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lang_id'], ['language.language_id'], ),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_table('word',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('word_name', sa.String(length=200), nullable=False),
    sa.Column('word_mean', sa.String(length=200), nullable=False),
    sa.Column('audio', sa.Text(), nullable=False),
    sa.Column('word_image', sa.Text(), nullable=False),
    sa.Column('lan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lan_id'], ['language.language_id'], ),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=False),
    sa.Column('group_image', sa.Text(), nullable=False),
    sa.Column('l_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['l_id'], ['level.level_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('lessons',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=200), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=False),
    sa.Column('g_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['g_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    op.drop_table('groups')
    op.drop_table('word')
    op.drop_table('level')
    op.drop_table('language')
    op.drop_table('countries')
    op.drop_table('user')
    op.drop_table('continents')
    # ### end Alembic commands ###
