"""questionnaire model changed

Revision ID: 883a0c11d5b3
Revises: 054b9f7815c1
Create Date: 2021-01-26 19:47:56.631223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883a0c11d5b3'
down_revision = '054b9f7815c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaires', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('questionnaires', sa.Column('language_id', sa.Integer(), nullable=True))
    op.add_column('questionnaires', sa.Column('level_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaires', 'level_id')
    op.drop_column('questionnaires', 'language_id')
    op.drop_column('questionnaires', 'group_id')
    # ### end Alembic commands ###
