"""ads model changedd

Revision ID: a0008c89ccc5
Revises: de21dde9cfca
Create Date: 2021-01-31 15:32:42.752120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0008c89ccc5'
down_revision = 'de21dde9cfca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('ad_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'ad_link')
    # ### end Alembic commands ###
