"""advertisement

Revision ID: a4f84135ca43
Revises: a6a44adf758d
Create Date: 2021-01-28 13:51:39.064972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f84135ca43'
down_revision = 'a6a44adf758d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisements',
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('ad_name', sa.String(length=200), nullable=False),
    sa.Column('ad_image', sa.Text(), nullable=False),
    sa.Column('ad_age_upper_limit', sa.Integer(), nullable=False),
    sa.Column('ad_age_lower_limit', sa.Integer(), nullable=False),
    sa.Column('ad_continent', sa.String(length=100), nullable=False),
    sa.Column('ad_gender', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ad_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisements')
    # ### end Alembic commands ###
