"""lessons model changed

Revision ID: c1d761150ef5
Revises: dfd616620647
Create Date: 2021-01-18 18:55:23.218242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d761150ef5'
down_revision = 'dfd616620647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('words_for_images', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'words_for_images')
    # ### end Alembic commands ###
