"""lessons model chnaged

Revision ID: dfd616620647
Revises: 540a290a4cf0
Create Date: 2021-01-17 15:42:37.359394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfd616620647'
down_revision = '540a290a4cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('images', sa.String(length=200), nullable=True))
    op.add_column('lessons', sa.Column('is_correct_character_selection', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('is_input_base_on_voice', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('is_multiple_images', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('is_pairs_to_match', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('is_single_image', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('is_straight_translation', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('is_tap_what_you_hear', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('is_write_this', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('options_tags', sa.String(length=200), nullable=True))
    op.add_column('lessons', sa.Column('sounds', sa.String(length=200), nullable=True))
    op.alter_column('word', 'language_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word', 'language_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('lessons', 'sounds')
    op.drop_column('lessons', 'options_tags')
    op.drop_column('lessons', 'is_write_this')
    op.drop_column('lessons', 'is_tap_what_you_hear')
    op.drop_column('lessons', 'is_straight_translation')
    op.drop_column('lessons', 'is_single_image')
    op.drop_column('lessons', 'is_pairs_to_match')
    op.drop_column('lessons', 'is_multiple_images')
    op.drop_column('lessons', 'is_input_base_on_voice')
    op.drop_column('lessons', 'is_correct_character_selection')
    op.drop_column('lessons', 'images')
    # ### end Alembic commands ###
