"""initial

Revision ID: f038c1a527aa
Revises: 
Create Date: 2021-01-26 14:33:13.504197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f038c1a527aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continents',
    sa.Column('continent_id', sa.Integer(), nullable=False),
    sa.Column('continent_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('continent_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=15), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('continent_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token')
    )
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=200), nullable=False),
    sa.Column('country_image', sa.Text(), nullable=False),
    sa.Column('continent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['continent_id'], ['continents.continent_id'], ),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('language',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=200), nullable=False),
    sa.Column('language_image', sa.Text(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('language_id')
    )
    op.create_table('level',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=200), nullable=False),
    sa.Column('level_image', sa.Text(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.language_id'], ),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_table('word',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('word_meaning', sa.String(length=200), nullable=False),
    sa.Column('audio', sa.Text(), nullable=True),
    sa.Column('word_image', sa.Text(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.language_id'], ),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=False),
    sa.Column('group_image', sa.Text(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.language_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.level_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('lessons',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=200), nullable=True),
    sa.Column('translation', sa.String(length=200), nullable=True),
    sa.Column('options_tags', sa.String(length=200), nullable=True),
    sa.Column('images', sa.String(length=200), nullable=True),
    sa.Column('sounds', sa.String(length=200), nullable=True),
    sa.Column('words_for_images', sa.String(length=200), nullable=True),
    sa.Column('is_straight_translation', sa.Integer(), nullable=True),
    sa.Column('is_multiple_images', sa.Integer(), nullable=True),
    sa.Column('is_single_image', sa.Integer(), nullable=True),
    sa.Column('is_pairs_to_match', sa.Integer(), nullable=True),
    sa.Column('is_input_base_on_voice', sa.Integer(), nullable=True),
    sa.Column('is_write_this', sa.Integer(), nullable=True),
    sa.Column('is_correct_character_selection', sa.Integer(), nullable=True),
    sa.Column('is_tap_what_you_hear', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.language_id'], ),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    op.drop_table('groups')
    op.drop_table('word')
    op.drop_table('level')
    op.drop_table('language')
    op.drop_table('countries')
    op.drop_table('users')
    op.drop_table('continents')
    # ### end Alembic commands ###
