"""models columns changed

Revision ID: f0bbd5eb32d4
Revises: 7de13f5bb471
Create Date: 2021-01-15 16:34:40.954382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0bbd5eb32d4'
down_revision = '7de13f5bb471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('continent_id', sa.Integer(), nullable=True))
    op.drop_constraint('countries_ibfk_1', 'countries', type_='foreignkey')
    op.create_foreign_key(None, 'countries', 'continents', ['continent_id'], ['continent_id'])
    op.drop_column('countries', 'cont_id')
    op.add_column('groups', sa.Column('level_id', sa.Integer(), nullable=True))
    op.drop_constraint('groups_ibfk_1', 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'level', ['level_id'], ['level_id'])
    op.drop_column('groups', 'l_id')
    op.add_column('language', sa.Column('country_id', sa.Integer(), nullable=True))
    op.drop_constraint('language_ibfk_1', 'language', type_='foreignkey')
    op.create_foreign_key(None, 'language', 'countries', ['country_id'], ['country_id'])
    op.drop_column('language', 'con_id')
    op.add_column('lessons', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('lessons_ibfk_1', 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'groups', ['group_id'], ['group_id'])
    op.drop_column('lessons', 'g_id')
    op.add_column('level', sa.Column('language_id', sa.Integer(), nullable=True))
    op.drop_constraint('level_ibfk_1', 'level', type_='foreignkey')
    op.create_foreign_key(None, 'level', 'language', ['language_id'], ['language_id'])
    op.drop_column('level', 'lang_id')
    op.add_column('word', sa.Column('language_id', sa.Integer(), nullable=True))
    op.add_column('word', sa.Column('word', sa.String(length=200), nullable=False))
    op.add_column('word', sa.Column('word_meaning', sa.String(length=200), nullable=False))
    op.drop_constraint('word_ibfk_1', 'word', type_='foreignkey')
    op.create_foreign_key(None, 'word', 'language', ['language_id'], ['language_id'])
    op.drop_column('word', 'word_name')
    op.drop_column('word', 'lan_id')
    op.drop_column('word', 'word_mean')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('word_mean', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('word', sa.Column('lan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('word', sa.Column('word_name', mysql.VARCHAR(length=200), nullable=False))
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.create_foreign_key('word_ibfk_1', 'word', 'language', ['lan_id'], ['language_id'])
    op.drop_column('word', 'word_meaning')
    op.drop_column('word', 'word')
    op.drop_column('word', 'language_id')
    op.add_column('level', sa.Column('lang_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'level', type_='foreignkey')
    op.create_foreign_key('level_ibfk_1', 'level', 'language', ['lang_id'], ['language_id'])
    op.drop_column('level', 'language_id')
    op.add_column('lessons', sa.Column('g_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key('lessons_ibfk_1', 'lessons', 'groups', ['g_id'], ['group_id'])
    op.drop_column('lessons', 'group_id')
    op.add_column('language', sa.Column('con_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'language', type_='foreignkey')
    op.create_foreign_key('language_ibfk_1', 'language', 'countries', ['con_id'], ['country_id'])
    op.drop_column('language', 'country_id')
    op.add_column('groups', sa.Column('l_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key('groups_ibfk_1', 'groups', 'level', ['l_id'], ['level_id'])
    op.drop_column('groups', 'level_id')
    op.add_column('countries', sa.Column('cont_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'countries', type_='foreignkey')
    op.create_foreign_key('countries_ibfk_1', 'countries', 'continents', ['cont_id'], ['continent_id'])
    op.drop_column('countries', 'continent_id')
    # ### end Alembic commands ###
